$python -m nose2
..F.F
======================================================================
FAIL: test_sum_2.transplant_class.<locals>.C (test_sum_tuple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dxc/Documents/Github/praxis-academy/novice/02-02/latihan/test_sum_2.py", line 5, in test_sum_tuple
    assert sum((1, 2, 2)) == 6, "Should be 6"
AssertionError: Should be 6

======================================================================
FAIL: test_sum_tuple (test_sum_unittest.TestSum)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dxc/Documents/Github/praxis-academy/novice/02-02/latihan/test_sum_unittest.py", line 9, in test_sum_tuple
    self.assertEqual(sum((1, 2, 2)), 6, "Should be 6")
AssertionError: 5 != 6 : Should be 6

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)